import os

from dotenv import load_dotenv

load_dotenv()
AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY")
AZURE_OPENAI_API_VERSION = os.getenv("AZURE_OPENAI_API_VERSION")
AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_API_EMBEDDING_MODEL = os.getenv("AZURE_OPENAI_API_EMBEDDING_MODEL")
AZURE_OPENAI_API_CHAT_MODEL = os.getenv("AZURE_OPENAI_API_CHAT_MODEL")
SOURCE_FILE_NAME = os.getenv("SOURCE_FILE_NAME")
